default: &default
  adapter: postgresql
  encoding: unicode
  host: integraciontarea2_db_1
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: myapp_development


test:
  <<: *default
  database: myapp_test
